// <auto-generated />
using System;
using EcoSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcoSystem.Models.CityData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CoalEnergyPercent")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PrivateGasPercent")
                        .HasColumnType("float");

                    b.Property<double>("PublicDieselPercent")
                        .HasColumnType("float");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoalEnergyPercent = 55.0,
                            Name = "Алматы қ.",
                            PrivateGasPercent = 15.0,
                            PublicDieselPercent = 10.0,
                            Region = "Мегаполис"
                        },
                        new
                        {
                            Id = 2,
                            CoalEnergyPercent = 87.0,
                            Name = "Астана қ.",
                            PrivateGasPercent = 6.0,
                            PublicDieselPercent = 45.0,
                            Region = "Мегаполис"
                        },
                        new
                        {
                            Id = 3,
                            CoalEnergyPercent = 25.0,
                            Name = "Шымкент қ.",
                            PrivateGasPercent = 47.0,
                            PublicDieselPercent = 5.0,
                            Region = "Мегаполис"
                        },
                        new
                        {
                            Id = 4,
                            CoalEnergyPercent = 97.0,
                            Name = "Қарағанды",
                            PrivateGasPercent = 5.0,
                            PublicDieselPercent = 85.0,
                            Region = "Қарағанды облысы"
                        },
                        new
                        {
                            Id = 5,
                            CoalEnergyPercent = 99.0,
                            Name = "Павлодар",
                            PrivateGasPercent = 4.0,
                            PublicDieselPercent = 82.0,
                            Region = "Павлодар облысы"
                        },
                        new
                        {
                            Id = 6,
                            CoalEnergyPercent = 65.0,
                            Name = "Өскемен",
                            PrivateGasPercent = 3.0,
                            PublicDieselPercent = 90.0,
                            Region = "Шығыс Қазақстан облысы"
                        },
                        new
                        {
                            Id = 7,
                            CoalEnergyPercent = 67.0,
                            Name = "Семей",
                            PrivateGasPercent = 4.0,
                            PublicDieselPercent = 88.0,
                            Region = "Абай облысы"
                        },
                        new
                        {
                            Id = 8,
                            CoalEnergyPercent = 48.0,
                            Name = "Талдықорған",
                            PrivateGasPercent = 20.0,
                            PublicDieselPercent = 75.0,
                            Region = "Жетісу облысы"
                        },
                        new
                        {
                            Id = 9,
                            CoalEnergyPercent = 92.0,
                            Name = "Жезқазған",
                            PrivateGasPercent = 5.0,
                            PublicDieselPercent = 90.0,
                            Region = "Ұлытау облысы"
                        },
                        new
                        {
                            Id = 10,
                            CoalEnergyPercent = 30.0,
                            Name = "Тараз",
                            PrivateGasPercent = 35.0,
                            PublicDieselPercent = 40.0,
                            Region = "Жамбыл облысы"
                        },
                        new
                        {
                            Id = 11,
                            CoalEnergyPercent = 20.0,
                            Name = "Қызылорда",
                            PrivateGasPercent = 43.0,
                            PublicDieselPercent = 10.0,
                            Region = "Қызылорда облысы"
                        },
                        new
                        {
                            Id = 12,
                            CoalEnergyPercent = 27.0,
                            Name = "Түркістан",
                            PrivateGasPercent = 45.0,
                            PublicDieselPercent = 35.0,
                            Region = "Түркістан облысы"
                        },
                        new
                        {
                            Id = 13,
                            CoalEnergyPercent = 0.0,
                            Name = "Орал",
                            PrivateGasPercent = 40.0,
                            PublicDieselPercent = 30.0,
                            Region = "Батыс Қазақстан облысы"
                        },
                        new
                        {
                            Id = 14,
                            CoalEnergyPercent = 0.0,
                            Name = "Ақтөбе",
                            PrivateGasPercent = 43.0,
                            PublicDieselPercent = 15.0,
                            Region = "Ақтөбе облысы"
                        },
                        new
                        {
                            Id = 15,
                            CoalEnergyPercent = 0.0,
                            Name = "Атырау",
                            PrivateGasPercent = 50.0,
                            PublicDieselPercent = 25.0,
                            Region = "Атырау облысы"
                        },
                        new
                        {
                            Id = 16,
                            CoalEnergyPercent = 0.0,
                            Name = "Ақтау",
                            PrivateGasPercent = 79.0,
                            PublicDieselPercent = 20.0,
                            Region = "Маңғыстау облысы"
                        },
                        new
                        {
                            Id = 17,
                            CoalEnergyPercent = 87.0,
                            Name = "Қостанай",
                            PrivateGasPercent = 5.0,
                            PublicDieselPercent = 78.0,
                            Region = "Қостанай облысы"
                        },
                        new
                        {
                            Id = 18,
                            CoalEnergyPercent = 95.0,
                            Name = "Петропавл",
                            PrivateGasPercent = 3.0,
                            PublicDieselPercent = 92.0,
                            Region = "Солтүстік Қазақстан облысы"
                        },
                        new
                        {
                            Id = 19,
                            CoalEnergyPercent = 97.0,
                            Name = "Көкшетау",
                            PrivateGasPercent = 4.0,
                            PublicDieselPercent = 85.0,
                            Region = "Ақмола облысы"
                        },
                        new
                        {
                            Id = 20,
                            CoalEnergyPercent = 57.0,
                            Name = "Қонаев",
                            PrivateGasPercent = 22.0,
                            PublicDieselPercent = 65.0,
                            Region = "Алматы облысы"
                        });
                });

            modelBuilder.Entity("EcoSystem.Models.SurveyResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcUsageMonths")
                        .HasColumnType("int");

                    b.Property<double>("AnnualBagPlasticGrams")
                        .HasColumnType("float");

                    b.Property<double>("AnnualCoffeePlasticGrams")
                        .HasColumnType("float");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Co2Trees")
                        .HasColumnType("int");

                    b.Property<int>("CoffeeCupsPerMonth")
                        .HasColumnType("int");

                    b.Property<double>("ConsumptionScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FlightsPerYear")
                        .HasColumnType("int");

                    b.Property<bool>("HasLedLights")
                        .HasColumnType("bit");

                    b.Property<bool>("HasRecycling")
                        .HasColumnType("bit");

                    b.Property<bool>("HasWaterMeter")
                        .HasColumnType("bit");

                    b.Property<string>("HeatingType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HousingType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("LivingScore")
                        .HasColumnType("float");

                    b.Property<double>("MobilityScore")
                        .HasColumnType("float");

                    b.Property<string>("ShoppingFrequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShoppingTripsPerWeek")
                        .HasColumnType("int");

                    b.Property<string>("SystemTag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalPlasticKg")
                        .HasColumnType("float");

                    b.Property<double>("TotalScore")
                        .HasColumnType("float");

                    b.Property<string>("TransportType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("WaterPools")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("SurveyResults");
                });
#pragma warning restore 612, 618
        }
    }
}
